# Site settings
title: Timmy liu
description: 不会打球的摄影狮不是一个好的程序猿

# User settings
username: DuncanTim21
nickname: Duncan - Timmy - liu
user_title: Software Developer
email: timmyliu21@163.com

exclude: ['package.json', 'src' , 'node_modules']
